### ISSUE TITLE
Utilizar arquivos stubs para facilitar a legibilidade do código

### ISSUE THREAD

**Issue by lincolnbrito** [phfoxer/laravel-api-generate#1]
Uma pequena sugestão seria usar arquivos *stubs* como o próprio gerador do Laravel utiliza. Fica mais legível e mais fácil adicionar outras funcionalidades no gerador. 

Evita casos como esse:

https://github.com/phfoxer/laravel-api-generate/blob/68c2d39554c73bc25fecb7c0d9dbb0212c774d15/src/ApiGenerate.php#L78-L82

**Comment by phfoxer** [comment]
Irei verificar as possibilidades. Se quiser contribuir com alterações no codigo, fique a vontade.
