### ISSUE TITLE
Class 'App\Modules\General\OwnerChannel\Models\OwnerChannel' not found

### ISSUE THREAD

**Issue by badrshs** [phfoxer/laravel-api-generate#2]
Hi , it seems like there is a problem , 

for me I have table called playlist  with an owner_channel_id attribute 

owner_channel_id  is not related to anything , it's just a number without any reference or foreign key , 

the problem is , your package assumed that there is a table with OwnerChannel Model , and it generate some reference to that  column , 
Class 'App\Modules\General\OwnerChannel\Models\OwnerChannel' not found
 
In reality , owner_channel_id  is only a number ( string )

-------------------------------------------
updated : 
same problem happen on user table , I have facebook_id , as string , and the package assumed that there is a facebook table too 😆

**Comment by phfoxer** [comment]
Thanks for your report, your issue has been resolved!

**Comment by phfoxer** [comment]
Now package verify if table reference exists.
