### ISSUE TITLE
 missing tag

### ISSUE THREAD

**Issue by leonardyrj** [phfoxer/laravel-api-generate#4]
Could not find a version of package phfoxer/apigenerate matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

**Comment by phfoxer** [comment]
What is your laravel version?

**Comment by leonardyrj** [comment]
5.8

Enviado do meu iPhone

Em 17 de out de 2019, à(s) 20:48, Paulo Henrique Santos <notifications@github.com> escreveu:

**Comment by phfoxer** [comment]
Resolved
